# Generated by Django 3.2 on 2021-04-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(verbose_name='date published')),
                ('link', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
