# Generated by Django 3.2 on 2021-04-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordrss',
            name='published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
