# Generated by Django 3.2 on 2021-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'email_addresses',
            },
        ),
        migrations.CreateModel(
            name='RunningFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=128)),
                ('module_name', models.CharField(max_length=128)),
                ('is_running', models.BooleanField()),
            ],
        ),
    ]
