# Generated by Django 3.2 on 2021-04-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uvz', '0002_alter_recordrss_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordRSS',
        ),
    ]
