# Generated by Django 3.2 on 2021-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvz', '0002_emailaddresses_runningfunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddresses',
            name='name',
            field=models.CharField(default='Undefined', max_length=128),
        ),
    ]
